"""add mention dedupe column + unique constraint

Revision ID: 1e6008f7ab66
Revises: 3849d0b59266
Create Date: 2026-06-09 17:58:51.521996
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

import app.core.security  # noqa: F401  (custom column types live here)


revision: str = '1e6008f7ab66'
down_revision: str | None = '3849d0b59266'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentions', sa.Column('platform_mention_id', sa.String(length=200), nullable=True))
    op.create_unique_constraint('uq_mentions_platform_id', 'mentions', ['politician_id', 'platform', 'platform_mention_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_mentions_platform_id', 'mentions', type_='unique')
    op.drop_column('mentions', 'platform_mention_id')
    # ### end Alembic commands ###
