"""initial 5 core tables

Revision ID: 3849d0b59266
Revises: 
Create Date: 2026-06-09 12:48:21.118094
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import app.core.security  # custom EncryptedString type used in column defs

revision: str = '3849d0b59266'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('bucket_hour', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sentiment_score', sa.Integer(), nullable=False),
    sa.Column('positive_count', sa.Integer(), nullable=False),
    sa.Column('negative_count', sa.Integer(), nullable=False),
    sa.Column('neutral_count', sa.Integer(), nullable=False),
    sa.Column('top_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_spike', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('politician_id', 'bucket_hour', name='uq_aggregates_pol_bucket')
    )
    op.create_index(op.f('ix_aggregates_politician_id'), 'aggregates', ['politician_id'], unique=False)
    op.create_table('audience_geo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('follower_pct', sa.Float(), nullable=True),
    sa.Column('age_band', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=16), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audience_geo_politician_id'), 'audience_geo', ['politician_id'], unique=False)
    op.create_table('mentions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=8), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=16), nullable=True),
    sa.Column('topics', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('inferred_city', sa.String(length=120), nullable=True),
    sa.Column('inferred_area', sa.String(length=120), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=False),
    sa.Column('platform_ts', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_mentions_pol_label_ts', 'mentions', ['politician_id', 'sentiment_label', 'platform_ts'], unique=False)
    op.create_index('ix_mentions_pol_processed', 'mentions', ['politician_id', 'processed'], unique=False)
    op.create_index(op.f('ix_mentions_politician_id'), 'mentions', ['politician_id'], unique=False)
    op.create_table('politicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('constituency', sa.String(length=200), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('ig_account_id', sa.String(length=100), nullable=True),
    sa.Column('fb_page_id', sa.String(length=100), nullable=True),
    sa.Column('meta_token', app.core.security.EncryptedString(length=2000), nullable=True),
    sa.Column('x_handle', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('politician_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=8), nullable=False),
    sa.Column('post_id', sa.String(length=120), nullable=False),
    sa.Column('reach', sa.Integer(), nullable=False),
    sa.Column('impressions', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('saves', sa.Integer(), nullable=False),
    sa.Column('react_like', sa.Integer(), nullable=False),
    sa.Column('react_love', sa.Integer(), nullable=False),
    sa.Column('react_angry', sa.Integer(), nullable=False),
    sa.Column('react_sad', sa.Integer(), nullable=False),
    sa.Column('react_haha', sa.Integer(), nullable=False),
    sa.Column('react_wow', sa.Integer(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_metrics_politician_id'), 'post_metrics', ['politician_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_metrics_politician_id'), table_name='post_metrics')
    op.drop_table('post_metrics')
    op.drop_table('politicians')
    op.drop_index(op.f('ix_mentions_politician_id'), table_name='mentions')
    op.drop_index('ix_mentions_pol_processed', table_name='mentions')
    op.drop_index('ix_mentions_pol_label_ts', table_name='mentions')
    op.drop_table('mentions')
    op.drop_index(op.f('ix_audience_geo_politician_id'), table_name='audience_geo')
    op.drop_table('audience_geo')
    op.drop_index(op.f('ix_aggregates_politician_id'), table_name='aggregates')
    op.drop_table('aggregates')
    # ### end Alembic commands ###
