import { getAIBrief } from "../lib/api";
import { usePolitician } from "../lib/PoliticianContext";
import { useData } from "../lib/useData";

export function AIBrief() {
  const { selected } = usePolitician();
  const { data, loading, error } = useData(() => getAIBrief(selected!.id), selected?.id);

  if (!selected) return <p className="text-slate-500">No connected account.</p>;
  if (loading) return <p className="text-slate-500">Loading brief…</p>;
  if (error || !data) return <p className="text-red-600">Could not load: {error}</p>;

  return (
    <div className="max-w-2xl space-y-6">
      <div>
        <h2 className="text-2xl font-semibold text-ink">AI Brief</h2>
        <p className="text-slate-500">
          Daily summary for {selected.name}
          {data.generated_at && (
            <span className="text-slate-400"> · {new Date(data.generated_at).toLocaleString()}</span>
          )}
        </p>
      </div>

      {!data.available && (
        <div className="rounded-lg border border-amber-200 bg-amber-50 px-4 py-2 text-sm text-amber-700">
          Not generated yet — the worker writes one per day.
        </div>
      )}

      <div className="glass-card sheen p-5">
        <div className="mb-2 text-sm font-medium text-slate-500">Summary</div>
        <p className="text-slate-800">{data.summary}</p>
      </div>

      {data.actions.length > 0 && (
        <div className="glass-card sheen p-5">
          <div className="mb-3 text-sm font-medium text-slate-500">Recommended actions</div>
          <ol className="list-decimal space-y-2 pl-5 text-slate-800">
            {data.actions.map((a, i) => (
              <li key={i}>{a}</li>
            ))}
          </ol>
        </div>
      )}
      <p className="text-xs text-slate-400">
        Generated by an LLM via OpenRouter from pre-computed aggregates (no external call on load).
      </p>
    </div>
  );
}
