import { getAIBrief } from "../lib/api";
import { usePolitician } from "../lib/PoliticianContext";
import { useData } from "../lib/useData";

export function AIBrief() {
  const { selected } = usePolitician();
  const { data, loading, error } = useData(() => getAIBrief(selected!.id), selected?.id);

  if (!selected) return <p className="text-mocha">No connected account.</p>;
  if (loading) return <p className="text-mocha">Loading brief…</p>;
  if (error || !data) return <p className="text-red-700">Could not load: {error}</p>;

  return (
    <div className="max-w-2xl space-y-5">
      <div>
        <h2 className="text-2xl font-extrabold text-ink">AI Brief</h2>
        <p className="text-coffee/70">
          Daily summary for {selected.name}
          {data.generated_at && (
            <span className="text-mocha"> · {new Date(data.generated_at).toLocaleString()}</span>
          )}
        </p>
      </div>

      {!data.available && (
        <div className="glass-card sheen px-4 py-2 text-sm text-coffee/80">
          Not generated yet — the worker writes one per day.
        </div>
      )}

      <div className="glass-card sheen p-5">
        <div className="mb-2 text-xs font-semibold uppercase tracking-wide text-mocha">Summary</div>
        <p className="leading-relaxed text-ink">{data.summary}</p>
      </div>

      {data.actions.length > 0 && (
        <div className="glass-card sheen p-5">
          <div className="mb-3 text-xs font-semibold uppercase tracking-wide text-mocha">
            Recommended actions
          </div>
          <ol className="space-y-2">
            {data.actions.map((a, i) => (
              <li key={i} className="glass-soft flex gap-3 rounded-lg p-3 text-ink">
                <span className="font-bold text-pulse">{i + 1}</span>
                <span>{a}</span>
              </li>
            ))}
          </ol>
        </div>
      )}
      <p className="text-xs text-mocha">
        Generated by an LLM via OpenRouter from pre-computed aggregates (no external call on load).
      </p>
    </div>
  );
}
