"""Public Voice, Trends, and AI Brief read endpoints (DB/Redis only — rule 1).

The AI Brief is READ from the Redis cache the worker fills; this endpoint never
calls the LLM itself, so the dashboard read path stays external-call-free.
"""

from __future__ import annotations

import csv
import io
import uuid
from datetime import timedelta

from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlalchemy import select
from sqlalchemy.orm import Session

from app.cache import cache_get
from app.core.timezone import floor_to_hour_ist, now_ist
from app.database import get_db
from app.models.aggregate import Aggregate
from app.models.mention import Mention
from app.models.politician import Politician
from app.models.post_metric import PostMetric
from app.schemas.content import (
    AIBriefOut,
    GeoCity,
    GeoOut,
    GroundInputIn,
    GroundInputOut,
    GrowthOut,
    GrowthPoint,
    MentionSample,
    MisinfoOut,
    PublicVoiceOut,
    TopicCount,
    TrendSeriesPoint,
    TrendsOut,
)
from app.services.geo_infer import CITY_COORDS, infer_location
from app.services.misinfo import detect_misinformation
from app.services.sentiment_reactions import classify_comment
from app.services.topics import dictionary_topics

router = APIRouter(prefix="/api", tags=["content"])


def _require(db: Session, politician_id: int) -> Politician:
    pol = db.get(Politician, politician_id)
    if pol is None:
        raise HTTPException(status_code=404, detail="politician not found")
    return pol


@router.get("/public-voice/{politician_id}", response_model=PublicVoiceOut)
def public_voice(politician_id: int, db: Session = Depends(get_db)) -> PublicVoiceOut:
    pol = _require(db, politician_id)
    recent = (
        db.execute(
            select(Mention)
            .where(Mention.politician_id == pol.id, Mention.raw_text.is_not(None))
            .order_by(Mention.platform_ts.desc().nullslast())
            .limit(200)
        )
        .scalars()
        .all()
    )

    by_sentiment: dict[str, int] = {"positive": 0, "negative": 0, "neutral": 0}
    by_platform: dict[str, int] = {}
    for m in recent:
        if m.sentiment_label in by_sentiment:
            by_sentiment[m.sentiment_label] += 1
        by_platform[m.platform] = by_platform.get(m.platform, 0) + 1

    # A balanced sample: a few of each sentiment for the feed.
    samples: list[MentionSample] = []
    for label in ("negative", "positive", "neutral"):
        for m in [x for x in recent if x.sentiment_label == label][:5]:
            samples.append(
                MentionSample(
                    text=m.raw_text or "",
                    sentiment_label=m.sentiment_label,
                    platform=m.platform,
                    likes=m.likes_count,
                    topics=m.topics or [],
                    platform_ts=m.platform_ts,
                )
            )
    return PublicVoiceOut(
        politician_id=pol.id,
        by_sentiment=by_sentiment,
        by_platform=by_platform,
        samples=samples,
        generated_at=now_ist(),
    )


@router.get("/trends/{politician_id}", response_model=TrendsOut)
def trends(politician_id: int, db: Session = Depends(get_db)) -> TrendsOut:
    pol = _require(db, politician_id)
    since = floor_to_hour_ist(now_ist()) - timedelta(hours=48)
    aggs = (
        db.execute(
            select(Aggregate)
            .where(Aggregate.politician_id == pol.id, Aggregate.bucket_hour >= since)
            .order_by(Aggregate.bucket_hour)
        )
        .scalars()
        .all()
    )

    topic_counts: dict[str, int] = {}
    series: list[TrendSeriesPoint] = []
    for a in aggs:
        for item in a.top_topics or []:
            topic_counts[item["topic"]] = topic_counts.get(item["topic"], 0) + item.get("count", 0)
        series.append(
            TrendSeriesPoint(
                bucket_hour=a.bucket_hour,
                total=a.positive_count + a.negative_count + a.neutral_count,
                positive=a.positive_count,
                negative=a.negative_count,
            )
        )
    top = sorted(topic_counts.items(), key=lambda kv: kv[1], reverse=True)[:10]
    return TrendsOut(
        politician_id=pol.id,
        top_topics=[TopicCount(topic=t, count=c) for t, c in top],
        series=series,
        generated_at=now_ist(),
    )


@router.get("/ai-brief/{politician_id}", response_model=AIBriefOut)
def ai_brief(politician_id: int, db: Session = Depends(get_db)) -> AIBriefOut:
    _require(db, politician_id)
    today = now_ist().date().isoformat()
    cached = cache_get(f"brief:{politician_id}:{today}")
    if not cached:
        return AIBriefOut(
            politician_id=politician_id,
            summary="Today's brief is being generated by the worker — check back shortly.",
            actions=[],
            generated_at=None,
            available=False,
        )
    return AIBriefOut(
        politician_id=politician_id,
        summary=cached["summary"],
        actions=cached.get("actions", []),
        generated_at=cached.get("generated_at"),
        available=True,
    )


@router.get("/geo/{politician_id}", response_model=GeoOut)
def geo(politician_id: int, db: Session = Depends(get_db)) -> GeoOut:
    """Per-city mention counts + sentiment for the India map (WP4/WP10)."""
    _require(db, politician_id)
    since = floor_to_hour_ist(now_ist()) - timedelta(hours=48)
    rows = (
        db.execute(
            select(Mention).where(
                Mention.politician_id == politician_id,
                Mention.inferred_city.is_not(None),
                Mention.platform_ts >= since,
            )
        )
        .scalars()
        .all()
    )

    agg: dict[str, dict[str, float]] = {}
    for m in rows:
        city = m.inferred_city or ""
        if city not in CITY_COORDS:
            continue
        d = agg.setdefault(city, {"mentions": 0, "negative": 0, "score_sum": 0.0})
        d["mentions"] += 1
        if m.sentiment_label == "negative":
            d["negative"] += 1
        d["score_sum"] += m.sentiment_score or 0.0

    cities = []
    for city, d in agg.items():
        lat, lon = CITY_COORDS[city]
        n = d["mentions"] or 1
        cities.append(
            GeoCity(
                city=city,
                lat=lat,
                lon=lon,
                mentions=int(d["mentions"]),
                negative=int(d["negative"]),
                avg_sentiment=round(d["score_sum"] / n, 3),
            )
        )
    cities.sort(key=lambda c: c.mentions, reverse=True)
    return GeoOut(politician_id=politician_id, cities=cities, generated_at=now_ist())


@router.get("/misinfo/{politician_id}", response_model=MisinfoOut)
def misinfo(politician_id: int, db: Session = Depends(get_db)) -> MisinfoOut:
    """Claim-volume misinformation flag (WP10)."""
    _require(db, politician_id)
    flag = detect_misinformation(db, politician_id)
    return MisinfoOut(
        politician_id=politician_id,
        flagged=flag.flagged,
        claim_volume=flag.claim_volume,
        window_hours=flag.window_hours,
        sample_texts=flag.sample_texts,
        generated_at=now_ist(),
    )


@router.get("/growth/{politician_id}", response_model=GrowthOut)
def growth(politician_id: int, db: Session = Depends(get_db)) -> GrowthOut:
    """Daily reach + engagement trend from post_metrics (WP4 'growth')."""
    _require(db, politician_id)
    since = floor_to_hour_ist(now_ist()) - timedelta(days=14)
    rows = (
        db.execute(
            select(PostMetric).where(
                PostMetric.politician_id == politician_id, PostMetric.captured_at >= since
            )
        )
        .scalars()
        .all()
    )

    by_day: dict[str, dict[str, int]] = {}
    for pm in rows:
        day = pm.captured_at.date().isoformat()
        d = by_day.setdefault(day, {"reach": 0, "engagement": 0})
        d["reach"] += pm.reach
        d["engagement"] += pm.likes + pm.comments_count + pm.shares + pm.saves
    series = [
        GrowthPoint(day=day, reach=v["reach"], engagement=v["engagement"])
        for day, v in sorted(by_day.items())
    ]
    return GrowthOut(politician_id=politician_id, series=series, generated_at=now_ist())


@router.post("/ground-input", response_model=GroundInputOut)
def ground_input(payload: GroundInputIn, db: Session = Depends(get_db)) -> GroundInputOut:
    """Manual ground-intelligence entry (fills the WhatsApp gap — no API exists).
    Stored in the unified mentions table (platform='ground') so it flows through
    the same sentiment/topic/geo pipeline."""
    _require(db, payload.politician_id)
    score, label = classify_comment(payload.text)
    topics = dictionary_topics(payload.text)
    city, area = infer_location(payload.text)
    city = city or payload.city
    mention = Mention(
        politician_id=payload.politician_id,
        platform="ground",
        source_type="mention",
        platform_mention_id=f"ground_{uuid.uuid4().hex}",
        raw_text=payload.text,
        language="und",
        sentiment_score=score,
        sentiment_label=label,
        topics=topics,
        inferred_city=city,
        inferred_area=area,
        likes_count=0,
        platform_ts=now_ist(),
        processed=True,
    )
    db.add(mention)
    db.commit()
    db.refresh(mention)
    return GroundInputOut(
        stored=True,
        mention_id=mention.id,
        sentiment_label=label,
        topics=topics,
        inferred_city=city,
    )


@router.get("/export/{politician_id}/mentions.csv")
def export_mentions_csv(politician_id: int, db: Session = Depends(get_db)) -> StreamingResponse:
    """Download recent mentions as CSV (WP11 reports)."""
    _require(db, politician_id)
    rows = (
        db.execute(
            select(Mention)
            .where(Mention.politician_id == politician_id)
            .order_by(Mention.platform_ts.desc().nullslast())
            .limit(1000)
        )
        .scalars()
        .all()
    )

    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(
        [
            "platform",
            "source_type",
            "sentiment_label",
            "sentiment_score",
            "topics",
            "inferred_city",
            "likes",
            "platform_ts",
            "text",
        ]
    )
    for m in rows:
        writer.writerow(
            [
                m.platform,
                m.source_type,
                m.sentiment_label,
                m.sentiment_score,
                "|".join(m.topics or []),
                m.inferred_city or "",
                m.likes_count,
                m.platform_ts.isoformat() if m.platform_ts else "",
                (m.raw_text or "").replace("\n", " "),
            ]
        )
    buf.seek(0)
    return StreamingResponse(
        iter([buf.getvalue()]),
        media_type="text/csv",
        headers={"Content-Disposition": f"attachment; filename=mentions_{politician_id}.csv"},
    )
